### ISSUE TITLE
about sup.reprompt_error in coffee machine example

### ISSUE THREAD

**Issue by shaolinkhoa** [dgtony/afg#2]
Hi,

Thank you for making afg. It's simple, easy to use.

In the coffee machine example, in ` @ask.intent('DrinkAmountIntent')` .
The function `sup.reprompt_error("I'm not sure, make it big or small?")` doesn't work. I didn't hear the reprompt_error

It's because in LIST_amount there are only "small" and "big". So If you say something new, which is not in the LIST_amount, Alexa will conflict and do nothing. So that state doesn't return the reprompt_error, I can ask help then it return the helpin scenario. : "Say: make small or make big" 

would you mind checking again.

Update #1: I added "on" and "off" to LIST_amount and the  the reprompt_error works correctly.
Do you have any solutions for this problem ?

thank you and regards,
Khoa

**Comment by dgtony** [comment]
Hi!
There was a bug in state machine rollback mechanism, I've fixed it and just released in version 0.2. Try it, maybe it will solve the problem.
Also I add sample Alexa intent schema into examples, please take a look.
And please mind: version 0.2 slightly breaks backwards compatibility, now in scenario description file instead of single reprompt and help phrases we use lists of variants to choose from. You can simply update your scenario to work with new afg.

**Comment by shaolinkhoa** [comment]
Hi @dgtony ,
Thank you for your help. 
I really don't understand what you mean "**slightly breaks backwards compatibility**" ?

**Comment by dgtony** [comment]
1) I mean that you just cannot use old scenario format with single phrases in help, default_help and reprompt fields, now it requires lists with at least one phrase.
2) afg supervisor will choose randomly one of the phrases from list.
3) The only way to jump to another state with user input is invocation of some allowed intent and it has nothing to do with afg supervisor. It seems that Alexa engine recognized your input as ChooseTeaIntent or ChooseCoffeeIntent and supervisor just followed the scenario.

**Comment by shaolinkhoa** [comment]
1/ So if a state don't have help phase, the afg supervisor will run default_help, right ? cause I'm still not sure how to jump to default_help. 

2/ I'm not sure but can we make afg supervisor have an option choose **in order** or **random** ? Cause I think it can make Alexa inteface with client better.

3/ Yeah, I will make more test and update later.

**Comment by dgtony** [comment]
1) Exactly, if help for the step is not defined, default_help will be picked.
2) Sorry, but I don't think it makes sense and I just don't want to overcomplicate scenarios with various options.

**Comment by shaolinkhoa** [comment]
Hi,
Would you mind adding the feature load render template in scenario to afg ? 
Cause when I'm in a state which I don't know. I want the help phase have full information so It's very long and inconvenience if in write in scenario

**Comment by dgtony** [comment]
Step-related help phrases, defined in scenario, intended to be used as a guidance for the user to invoke right skill. In case you want to tell some dynamically changing information to user, I believe it’s better to use special handler for Amazon.HelpIntent, that will render data according to current step. Current scenario step you can get with supervisor’s method *get_current_state*.

**Comment by shaolinkhoa** [comment]
Hi,
Can I make the state jump back to it previous state.
Ex:
```
  **center:**
    # if wrong intent was invoked, ask user again with one of the phrases (random choice)
    reprompt:
      - "Sorry, I didn't understand"
      - "Please ask help for more information"
    # help phrases for the current step
    help:
      - "If you to know more about me, just say Who are you. To control device, just say turn on the light. To read sensor value, just say read the Temperature. To Set the value of device, just say Set the Air Conditioner to twenty."
      - "Just say: Who are you"
      - "Just say: turn on the light"
      - "If you don't have any commands, just say stop."
    events:
      # event trigger #1
      PlayMusicIntent_trigger: # def function
        # where to move from here?
        next: waiting #ChooseSongs_choice
      # event trigger #2
      ControlDeviceIntent_trigger: # def function
        next: waiting #ControlDeviceIntent_choice
      ReadSensorIntent_trigger:
        next: waiting #ReadSensorIntent_choice
      SetSensorIntent_trigger:
        next: waiting #SetSensorIntent_choice
      IntrocdutionIntent_trigger:
        next: waiting #SetSensorIntent_choice
      stop:
        next: done
  
  **waiting**:
    reprompt:
      - "Sorry, I didn't understand"
      - "Please ask help for more information"
    # help phrases for the current step
    help:
      - "I am waiting for your next command. Just ask and I will do it for you. If you don't have any more command, just say stop."
      - "If you don't have any more command, just say stop."
      - "You can ask for more command, I will do it for you."
    events:
      # event trigger #1
      PlayMusicIntent_trigger: # def function
        # where to move from here?
        next: center #ChooseSongs_choice
      # event trigger #2
      ControlDeviceIntent_trigger: # def function
        next: center #ControlDeviceIntent_choice
      ReadSensorIntent_trigger:
        next: center #ReadSensorIntent_choice
      SetSensorIntent_trigger:
        next: center #SetSensorIntent_choice
      IntrocdutionIntent_trigger:
        next: center #SetSensorIntent_choice
      stop:
        next: done
```

```
@ask.intent('AMAZON.StopIntent')
@sup.guide
def stop():
    close_user_session()
    return statement(render_template('stop')) 

Only  **stop()** has `close_user_session()`. But It didn't work. Alexa stop the skill after I finished the first command.
```

**Comment by dgtony** [comment]
Supervisor’s state machine keeps transition history and to move one step back you can use method _reprompt_error_: it rollback state machine and return _question_-object with given message. If method was called without message it will return one of reprompts defined for current step
In case you want to move to arbitrary step according to some dynamically changing information and it would be hard to squeeze this logic into scenario you can use method _move_to_step_ and give it explicitly name of the step to move on.
Also, it seems to me that user should be able to interrupt session at any step, so maybe it is better to leave stop-handler as a free method and do not guide it with supervisor (unless you use cancel-handler for the interruption purpose).

**Comment by shaolinkhoa** [comment]
I did: 
Create a `ContinueIntent` to ask continue the skill or not.
I used _move_to_step_ in the `ContinueIntent` to jump back to the previous step.

**my Scenario:**
```
first_step: init 
last_step: done
default_help:
  - "You are talking to Alexa. What would you like to do ?"
  - "Hi, I'm your assistant, Which devices you want to control ?"

steps:
  # the first step
  init:
    events:
      launched: 
        next: center 

  # step name
  center:
    reprompt:
      - "Sorry, I didn't understand"
      - "Please ask help for more information"
    help:
      - "If you to know more about me, just say Who are you. To control device, just say turn on the light. To read sensor value, just say read the Temperature. To Set the value of device, just say Set the Air Conditioner to twenty."
      - "Just say: Who are you"
      - "Just say: turn on the light"
      - "If you don't have any commands, just say stop."
    events:
      PlayMusicIntent_trigger: # def function
        next: waiting #ChooseSongs_choice
      ControlDeviceIntent_trigger:
        next: waiting 
      ReadSensorIntent_trigger:
        next: waiting
      SetSensorIntent_trigger:
        next: waiting 
      IntrocdutionIntent_trigger:
        next: waiting
  
  waiting:
    reprompt:
      - "Sorry, I didn't understand"
      - "Please ask help for more information"
    help:
      - "I am waiting for your next command. Just say yes then ask. I will do it for you. If you don't have any more command, just say no."
      - "If you don't have any more command, just say stop."
      - "You can ask for more command, I will do it for you. Just say yes."
    events:
      ContinueIntent_trigger: # def function
        next: done 
 
# no need to describe last step
  done:
```

My code:
```
#### Begin waiting state ####
@ask.intent('ContinueIntent')
@sup.guide
def ContinueIntent_trigger(Answer):

    if Answer in ['yes','sure']:
        sup.move_to_step('center')
        return statement(render_template('Continue_return'))

    close_user_session()
    return statement(render_template('stop'))

#### End waiting state ####
```
the flask-ask web always return `"shouldEndSession": true` after I finished **center** state

**Comment by shaolinkhoa** [comment]
Hi,
I know why my web server send `"shouldEndSession": true`

Because I use `return statement("do you want to continue")` and the function statement() in flask-ask always return `"shouldEndSession": true`

```
class statement(_Response):

    def __init__(self, speech):
        super(statement, self).__init__(speech)
        self._response['shouldEndSession'] = True
```
